### ISSUE TITLE
Highlighting of the data in blue colour should be removed where ever row pop-out is present 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#2486]
1. Highlighting of the data in blue colour should be removed where ever row pop-out is present 
2. Row pop-out should be as per invision screen

[Note : It should be handled in all the pages where ever row pop-out is present]

![row pop-up](https://user-images.githubusercontent.com/71445210/102527056-96a28b00-40c2-11eb-8fa5-9188ba427fa0.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue issue is fixed in latest QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV- QA its fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 
Highlighting of the data in blue colour should be removed where ever row pop-out is present - fixed
Row pop-out should be as per invision screen - Not fixed

**Comment by Lathan-btc** [comment]
Issue is fixed in latest Dev instance.
