### ISSUE TITLE
[SB] Add info icon text for notification scheduling

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3160]
For the Create, Edit, Resend and View notification screens (for app level as well as study-level notifications)  > Add an info icon next to 'Schedule notification' with following text 'The notification gets delivered to mobile app users at the selected date and time as per server time zone which is <server time zone>' - display the dynamically read server time zone value here, which is also being displayed in activity scheduling

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm

**Comment by Lathan-btc** [comment]
@Kantharajut-btc 
1. Add a full stop at the end of the info icon text to maintain cosistancy
2. App level notifications > Reduce the height and increase the width of the info icon text layout 

![info2](https://user-images.githubusercontent.com/71445210/107918724-32038f80-6f90-11eb-9a55-c06343a433c0.png)

**Comment by Kantharajut-btc** [comment]
@Madhud5 changes from backend are done, please change the width of the tool tip and assign back to QA, thank you

**Comment by Madhud5** [comment]
Hi @Lathan-btc its fixed in DEV env pls check into this.

**Comment by aswinijena100** [comment]
@Lathan-btc Please check this issue in QA and close if fixed

**Comment by Lathan-btc** [comment]
@Madhud5 
1. Add a full stop at the end of the info icon text to maintain consistency - fixed
2. App-level notifications > Reduce the height and increase the width of the info icon text layout - Not fixed in both Dev and QA instances

**Comment by Lathan-btc** [comment]
@harisboston Adjust the gap between text and icon for both study level and app level notifications.



![img32](https://user-images.githubusercontent.com/71445210/124283102-27c1e680-db69-11eb-8994-aae07ac444ed.png)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by bhoomikav16** [comment]
Issue is not fixed in the qa instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the qa instance
