### ISSUE TITLE
[PM] UI Issues in password strength meter 

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3255]
UI Issues in password strength meter:

1. Strength meter should be as per UI design i.e length of meter should display below New password field completely
2. Width of meter should be increased i.e as per design
3. Text 'Weak'/'Fair'/'Goog'/'Strong' font size should be increased
4. Colour of top portion of meter is not filled completely 
5. Font colour for Green and Red is different compared to design

![Screenshot_3](https://user-images.githubusercontent.com/60386291/109014048-c8932780-76d9-11eb-916c-5a4ce0f2d195.png)

**Comment by Madhud5** [comment]
Hi @fahad-kc @fahadbtc-zz, Can you provide UI for the above.

**Comment by fahad-kc** [comment]
@Madhud5 Provided already

**Comment by Madhud5** [comment]
Hi @nishit-v I have fixed it in dev env. Please check.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it in dev env. Please check.

**Comment by Lathan-btc** [comment]
@Madhud5 
1.Font color for Green and Red is different compared to the design
2. Height of the meter should be reduced
3. Set up account screen > Text 'Weak'/'Fair'/'Goog'/'Strong' should be displayed as per invision screen
4. Set up account screen > Adjust the alignment of the Error message

![pwd meter2](https://user-images.githubusercontent.com/71445210/110490259-22eaaa00-8116-11eb-82d4-df932f0baf0a.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc   DEV- QA its fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 

Issue is still reproducible in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc DEV- QA its fixed. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Font color for Green and Red is different compared to the design: Issue is reproducible only in firefox browser

![ss13](https://user-images.githubusercontent.com/71445210/111628209-f883a580-8815-11eb-9c95-7f8223a540c8.png)

**Comment by Madhud5** [comment]
Hi, @SR-btc  Firefox won't support meter progress bar color difference. please let me know if the above image is fine.

**Comment by Madhud5** [comment]
Hi @latha please look into this issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. PR merged Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
