### ISSUE TITLE
[Mobile apps] app is getting crashed when user clicks on the study

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3697]
Steps
1. Login to SB 
2. Add any activity with a custom schedule for the study 
3. Launch/publish updates
4. In the mobile app click on the particular study for which custom activity is added  
5. Observe

AR: App is getting crashed
ER: App should not be crashed

![image](https://user-images.githubusercontent.com/71445210/120890284-362aea00-c61f-11eb-8883-58e2e29a6df5.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in dev environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
@GovindPrasadBostonTechnologyCorporation iOS App is crashing on navigating to study activities list having custom schedule activities configured

**Comment by Lathan-btc** [comment]
@naveenr-btc App crashing issue is fixed in the latest android build.

**Comment by nishit-v** [comment]
@GovindPrasadBostonTechnologyCorporation iOS app is crashing for anchor based activities.

Enroll into study Custom schedule study(Original) > Click on 'source' activity --> enter the date and click on submit --> app crashes

Study details:
Study name: Custom schedule study(Original

**Comment by harisboston** [comment]
@nishit-v Please confirm, whether iOS app is still crashing for above scenario. Thanks.

**Comment by nishit-v** [comment]
@harisboston Issue is still reproducible in iOS

iOS app is crashing for anchor based activities.

Enroll into study  > Click on 'source' activity --> enter the date and click on submit --> app crashes

Study details:
Study name: Activity study

**Comment by nishit-v** [comment]
@harisboston @GovindPrasadBostonTechnologyCorporation Crash issue is resolved in the latest dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in Android and iOS latest QA builds.
