### ISSUE TITLE
[PM] Set up account screen > Password field > Error message is not getting dispalyed when there is no data in the field

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4419]
Set up account screen > Password field > Error message is not getting dispalyed when there is no data in the field

**AR:** Error message is not getting displayed when there is no data.
**ER:**  Error message should get displayed when there is no data.
![ee](https://user-images.githubusercontent.com/86007179/152520450-5eac8416-48d9-487d-b6f7-467b1b2e4a99.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in Dev instance

**Comment by bhoomikav16** [comment]
@madhurya-btc Issue is still reproducing in the latest dev instance.

**Comment by Rashi-395** [comment]
@bhoomikav16 Set up account screen > Password field > Error message is not getting dispalyed when there is no data in the field
is fixed in latest DEV instance . Please test

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
@madhurya-btc Issue is still reproducing in the latest QA instance.

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
