### ISSUE TITLE
[FHIR] All the created activities in the study builder are not mapping into the FHIR datastore

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#4746]
Steps:
1. Create multiple activities in SB and launch the study [Created around 15 to 20 activities in SB]
2. Go to the google cloud console
3. Search for FHIR viewer
4. Click on the particular dataset and click on the FHIR datastore
5. Search for the Questionnaire and click on it 
6. Observe 

AR: All the activities created in the Study builder are not getting mapped in to the Questionnaire of the FHIR datastore
ER: All the activities created in the SB should get mapped into FHIR store  (As per above scenario only 6 activities are mapped into FHIR store)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance, refer the following study

Study id: imported0208
Study name: FHIR_DID-Study (All response types)[imported0208]

**Comment by Lathan-btc** [comment]
@harisboston This issue is happening because of the Boolean response type, please check

**Comment by harisboston** [comment]
@Lathan-btc Updated, deployed in dev env. Please confirm.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by Lathan-btc** [comment]
@harisboston Issue is reproducible for Active tasks in the latest Dev instance

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest DEV instance

**Comment by bhoomikav16** [comment]
Issue is reproducible in the latest DEV instance

**Comment by bhoomikav16** [comment]
Issue is still reproducible for anchor data custom scheduling activities in the latest DEV instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
